# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos6.4"
  config.vm.provision :puppet do |puppet|
    puppet.module_path = "modules"
  end
  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.customize ["modifyvm", :id, "--memory", "8192", "--vram", "12"]
  end
end
